values: |
  replicaCount: 4
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
  ingress:
    enabled: false
    annotations: {}
    hosts:
      - host: chart-example.coinesto.com
        paths: []
    tls: []
