values: |
  fullnameOverride: test-ne
  image:
    pullPolicy: Always
  replicaCount: 2
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
  ingress:
    hosts:
      - host: chart-example.coinesto.com.vn
